TimLeach635/WhaleSpotting-OpenCohort2023

- WhaleSpotting/Data/ApplicationDbContext.cs
- WhaleSpotting/Migrations/20231106110601_AddSightingTable.Designer.cs
- WhaleSpotting/Migrations/20231106110601_AddSightingTable.cs
- WhaleSpotting/Models/Sighting.cs
Add a `Sighting.cs` C# model and create a migration for adding it into the database
> WS-001: Create "Sighting" model

- WhaleSpotting/Data/ApplicationDbContext.cs
- WhaleSpotting/Migrations/20231106115621_AddSpeciesTable.Designer.cs
- WhaleSpotting/Migrations/20231106115621_AddSpeciesTable.cs
- WhaleSpotting/Models/Species.cs
Add a `Species.cs` C# model and create migration for adding to database
> WS-027: Create species model

- WhaleSpotting/Controllers/SpeciesController.cs
> WS-010: Add Species Controller

- WhaleSpotting/Controllers/SightingController.cs
Create basic sighting controller
> WS-002: Create basic sighting controller

- WhaleSpotting/Controllers/SightingController.cs
Add Sighting List Endpoint on Sighting Controller
> WS-015 sighting list endpoint

- WhaleSpotting/Controllers/SightingController.cs
> WS-013: Create new sighting endpoint

- WhaleSpotting/Models/Website.cs
> WS-000: Fix spacing

- WhaleSpotting/Controllers/SpeciesController.cs
Add route to Species controller to avoid bug where all routes were being rerouted to the species controller and interpreted as an id
> WS-000: Bug fix

- WhaleSpotting/Views/Species/Index.cshtml
- WhaleSpotting/Views/Species/UniqueSpecies.cshtml
Created a page with list of Whales and links to each whales on its on page.
> WS 033 create page of whales with images

- WhaleSpotting/Views/Species/Index.cshtml
- WhaleSpotting/Views/Species/Species.cshtml
Realised I had an extra view page so have deleted that and fixed a link in the other
> WS 033 amend species views

- WhaleSpotting/Views/Sighting/Index.cshtml
Created a basic list of sightings. 
Needs more work done: 
1. Polish the appearance of the cards.
2. Not sure what information should appear on the card.
3. Amend to show a list of cards in a slide show format. 
4. Include a photo.
> WS-028: Create List of Sightings Page - Create Cards

- WhaleSpotting/Views/Sighting/Index.cshtml
Add labels for fields on list of sightings cards
> WS-042: List of Sightings Page - Add labels for fields

- WhaleSpotting/Controllers/SpeciesController.cs
- WhaleSpotting/Migrations/20231108115541_AddSlugsToSpecies.Designer.cs
- WhaleSpotting/Migrations/20231108115541_AddSlugsToSpecies.cs
- WhaleSpotting/Models/Species.cs
- WhaleSpotting/Views/Species/Index.cshtml
changing it so that you can put the slug of the species in the navigation URL instead of the Id
> WS-024-IdToSlugs

- WhaleSpotting/Migrations/20231108142804_AddDetailsToWsUser.Designer.cs
- WhaleSpotting/Migrations/20231108142804_AddDetailsToWsUser.cs
- WhaleSpotting/Models/WsUser.cs
Add name, profile pic, and bio columns to the user model
> WS-000: Add details to WsUser model

- WhaleSpotting/Views/Views/Sighting/NewSightingForm.cshtml
ws-029: New Sighting Form - Create Form and ws-014: New sighting form endpoint
> Sighting Form - Create Form

- WhaleSpotting/Views/User/UserPage.cshtml
Added a list of sightings to the users own user page.
> WS - 005 list of users sightings on user profile

- WhaleSpotting/Controllers/SightingController.cs
- WhaleSpotting/Views/Sighting/Index.cshtml
Added a user field to the list of sightings cards.
> WS-043: List of Sightings Page - Add user field

- WhaleSpotting/Controllers/UserController.cs
Endpoint to take the user page changes and add to the database
> WS-022: Edit user endpoint

- WhaleSpotting/Controllers/SightingController.cs
- WhaleSpotting/Views/Sighting/NewSightingForm.cshtml
1. Title added to form
2. Spacing added to elements
Input for photo not added.
A new card will be created to add functionality to upload photos
> WS-030: New Sighting Form - Add input fields

- WhaleSpotting/Controllers/AdminController.cs
- WhaleSpotting/Views/Admin/Index.cshtml
Admin page added & review form created
> Ws 044 sightings review

- WhaleSpotting/Views/User/UserPage.cshtml
- WhaleSpotting/wwwroot/css/site.css
Added name, profile picture and bio to user
> WS-006: display user items in profile

- WhaleSpotting/Controllers/UserController.cs
- WhaleSpotting/Views/User/EditUser.cshtml
Edit user endpoint to set the template for amendable user details e.g. username, email etc. updates
> WS-021: Edit user page endpoint

- WhaleSpotting/Areas/Identity/Pages/Account/Register.cshtml.cs
Creates a new wsuser in WsUser database.
Only adds a unique userid.
All other fields are empty at present.
> WS-060: Create a wsuser when a user registers

- WhaleSpotting/Controllers/SightingController.cs
- WhaleSpotting/Views/Home/Index.cshtml
Amend sighting link from home page depending on login
> WS 054 amend sighting link

- WhaleSpotting/Views/Shared/_Layout.cshtml
- WhaleSpotting/Views/Species/Index.cshtml
- WhaleSpotting/wwwroot/css/site.css
Cleaned up species page and also hover effect on home page buttons
> WS 064 clean up species page

- WhaleSpotting/Views/Home/Index.cshtml
- WhaleSpotting/Views/Species/UniqueSpecies.cshtml
- WhaleSpotting/wwwroot/css/site.css
Cleaned up individual species page and some of the home page
> Ws 069 clean up individual species page

- WhaleSpotting/Controllers/SightingController.cs
- WhaleSpotting/Views/Shared/_MyListPartial.cshtml
created filter to filter by species on sighting index page for list tab
> ws-032-SpeciesFilter

- WhaleSpotting/Views/Species/Index.cshtml
- WhaleSpotting/wwwroot/css/site.css
Added small CSS to improve look
> WS 070 alter css as advised

- WhaleSpotting/Controllers/SightingController.cs
- WhaleSpotting/Models/Sighting.cs
- WhaleSpotting/Models/SightingViewModel.cs
- WhaleSpotting/ViewModels/NewSightingFormViewModel.cs
- WhaleSpotting/Views/Sighting/NewSightingForm.cshtml
Add SightingViewModel to input DateTime and convert to DateOnly
> Add SIghting View Model to convert DateTime to DateOnly

- WhaleSpotting/Controllers/SightingController.cs
Fix bug where the new sighting form redirected to a nonexistent page after submission
> WS-075: Fix new sighting form redirect

- WhaleSpotting/Controllers/AdminController.cs
- WhaleSpotting/Models/Sighting.cs
- WhaleSpotting/Views/Admin/Index.cshtml
- WhaleSpotting/Views/Shared/_Layout.cshtml
- WhaleSpotting/Views/Sighting/Index.cshtml
- WhaleSpotting/Views/User/UserPage.cshtml
Add Nullable reference types & amend partial name syntax to remove warnings
> Remove warnings

- WhaleSpotting/Controllers/AdminController.cs
- WhaleSpotting/Views/Admin/Index.cshtml
- WhaleSpotting/wwwroot/js/site.js
Add a delete button that removes sightings in the admin page.
> WS073: Delete button
